<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.javalin</groupId>
        <!-- 特别注意：真实的业务系统应继承 ddd4j-javalin-parent  -->
        <artifactId>ddd4j-javalin-samples</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>ddd4j-javalin-sample-hikaricp</artifactId>

    <dependencies>
        <!-- For Javalin -->
        <dependency>
            <groupId>io.ddd4j.javalin</groupId>
            <artifactId>ddd4j-javalin-api</artifactId>
            <version>${ddd4j-javalin.version}</version>
        </dependency>
        <dependency>
            <groupId>io.ddd4j.javalin</groupId>
            <artifactId>ddd4j-javalin-guice-autoconfigure</artifactId>
            <version>${ddd4j-javalin.version}</version>
        </dependency>
        <!-- For H2 -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- For Dozer -->
        <dependency>
            <groupId>com.github.dozermapper</groupId>
            <artifactId>dozer-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.ddd4j.javalin</groupId>
            <artifactId>dozer-extra-converters</artifactId>
        </dependency>
        <!-- For Redis -->
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </dependency>
        <!-- For Log4j2 -->
        <!-- For Logback -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <!-- For Mybatis -->
        <!-- For Jooq -->
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-codegen</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- For HikariCP -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <!-- JDBC Driver For MySQL -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- JDBC Driver For Oracle -->
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.observability</groupId>
            <artifactId>ojdbc8dms</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.nls</groupId>
            <artifactId>orai18n</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- For Embedded Web -->
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-instrumentation-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-exporter-servlet-jakarta</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <!-- 第一步：生成可执行的启动脚本 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>appassembler-maven-plugin</artifactId>
            </plugin>
            <!-- 第一步：通过antrun插件拷贝文件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
            </plugin>
            <!-- 第三步：通过docker-maven插件构造Docker镜像
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
            </plugin> -->
            <!-- 第四步：生成离线文档-->
            <!-- http://blog.didispace.com/swagger2markup-asciidoc/ -->
            <!-- First, use the swagger2markup plugin to generate asciidoc
            <plugin>
                <groupId>io.github.swagger2markup</groupId>
                <artifactId>swagger2markup-maven-plugin</artifactId>
            </plugin>-->
            <!-- Run the generated asciidoc through Asciidoctor to generate other
                documentation types, such as PDFs or HTML5
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
            </plugin> -->
        </plugins>
    </build>

</project>
