/*
 * This file is generated by jOOQ.
 */
package io.javalin.sample.db.write.tables.records;


import io.javalin.sample.db.write.tables.User;
import io.javalin.sample.db.write.tables.pojos.UserPo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record19<Long, Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, Integer, String, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>t_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>t_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>t_user.version</code>. 版本
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>t_user.version</code>. 版本
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>t_user.client_user_id</code>. 小程序用户ID
     */
    public void setClientUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>t_user.client_user_id</code>. 小程序用户ID
     */
    public String getClientUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>t_user.level</code>. 等级
     */
    public void setLevel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>t_user.level</code>. 等级
     */
    public Integer getLevel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>t_user.user_name</code>. userName
     */
    public void setUserName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>t_user.user_name</code>. userName
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>t_user.ip</code>. IP
     */
    public void setIp(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>t_user.ip</code>. IP
     */
    public String getIp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>t_user.country</code>. Country
     */
    public void setCountry(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>t_user.country</code>. Country
     */
    public String getCountry() {
        return (String) get(6);
    }

    /**
     * Setter for <code>t_user.city</code>. city
     */
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>t_user.city</code>. city
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>t_user.region</code>. region
     */
    public void setRegion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>t_user.region</code>. region
     */
    public String getRegion() {
        return (String) get(8);
    }

    /**
     * Setter for <code>t_user.first_name</code>. firstName
     */
    public void setFirstName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>t_user.first_name</code>. firstName
     */
    public String getFirstName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>t_user.last_name</code>. lastName
     */
    public void setLastName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>t_user.last_name</code>. lastName
     */
    public String getLastName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>t_user.language_code</code>. languageCode
     */
    public void setLanguageCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>t_user.language_code</code>. languageCode
     */
    public String getLanguageCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>t_user.latitude</code>. latitude
     */
    public void setLatitude(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>t_user.latitude</code>. latitude
     */
    public String getLatitude() {
        return (String) get(12);
    }

    /**
     * Setter for <code>t_user.longitude</code>. longitude
     */
    public void setLongitude(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>t_user.longitude</code>. longitude
     */
    public String getLongitude() {
        return (String) get(13);
    }

    /**
     * Setter for <code>t_user.status</code>.  状态
     */
    public void setStatus(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>t_user.status</code>.  状态
     */
    public Integer getStatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>t_user.type</code>. 类型
     */
    public void setType(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>t_user.type</code>. 类型
     */
    public String getType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>t_user.channel</code>. 渠道
     */
    public void setChannel(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>t_user.channel</code>. 渠道
     */
    public String getChannel() {
        return (String) get(16);
    }

    /**
     * Setter for <code>t_user.created_at</code>. 创建时间
     */
    public void setCreatedAt(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>t_user.created_at</code>. 创建时间
     */
    public Long getCreatedAt() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>t_user.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>t_user.updated_at</code>. 更新时间
     */
    public Long getUpdatedAt() {
        return (Long) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, Integer, String, String, Long, Long> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, Integer, String, String, Long, Long> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return User.USER.VERSION;
    }

    @Override
    public Field<String> field3() {
        return User.USER.CLIENT_USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return User.USER.LEVEL;
    }

    @Override
    public Field<String> field5() {
        return User.USER.USER_NAME;
    }

    @Override
    public Field<String> field6() {
        return User.USER.IP;
    }

    @Override
    public Field<String> field7() {
        return User.USER.COUNTRY;
    }

    @Override
    public Field<String> field8() {
        return User.USER.CITY;
    }

    @Override
    public Field<String> field9() {
        return User.USER.REGION;
    }

    @Override
    public Field<String> field10() {
        return User.USER.FIRST_NAME;
    }

    @Override
    public Field<String> field11() {
        return User.USER.LAST_NAME;
    }

    @Override
    public Field<String> field12() {
        return User.USER.LANGUAGE_CODE;
    }

    @Override
    public Field<String> field13() {
        return User.USER.LATITUDE;
    }

    @Override
    public Field<String> field14() {
        return User.USER.LONGITUDE;
    }

    @Override
    public Field<Integer> field15() {
        return User.USER.STATUS;
    }

    @Override
    public Field<String> field16() {
        return User.USER.TYPE;
    }

    @Override
    public Field<String> field17() {
        return User.USER.CHANNEL;
    }

    @Override
    public Field<Long> field18() {
        return User.USER.CREATED_AT;
    }

    @Override
    public Field<Long> field19() {
        return User.USER.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getClientUserId();
    }

    @Override
    public Integer component4() {
        return getLevel();
    }

    @Override
    public String component5() {
        return getUserName();
    }

    @Override
    public String component6() {
        return getIp();
    }

    @Override
    public String component7() {
        return getCountry();
    }

    @Override
    public String component8() {
        return getCity();
    }

    @Override
    public String component9() {
        return getRegion();
    }

    @Override
    public String component10() {
        return getFirstName();
    }

    @Override
    public String component11() {
        return getLastName();
    }

    @Override
    public String component12() {
        return getLanguageCode();
    }

    @Override
    public String component13() {
        return getLatitude();
    }

    @Override
    public String component14() {
        return getLongitude();
    }

    @Override
    public Integer component15() {
        return getStatus();
    }

    @Override
    public String component16() {
        return getType();
    }

    @Override
    public String component17() {
        return getChannel();
    }

    @Override
    public Long component18() {
        return getCreatedAt();
    }

    @Override
    public Long component19() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getClientUserId();
    }

    @Override
    public Integer value4() {
        return getLevel();
    }

    @Override
    public String value5() {
        return getUserName();
    }

    @Override
    public String value6() {
        return getIp();
    }

    @Override
    public String value7() {
        return getCountry();
    }

    @Override
    public String value8() {
        return getCity();
    }

    @Override
    public String value9() {
        return getRegion();
    }

    @Override
    public String value10() {
        return getFirstName();
    }

    @Override
    public String value11() {
        return getLastName();
    }

    @Override
    public String value12() {
        return getLanguageCode();
    }

    @Override
    public String value13() {
        return getLatitude();
    }

    @Override
    public String value14() {
        return getLongitude();
    }

    @Override
    public Integer value15() {
        return getStatus();
    }

    @Override
    public String value16() {
        return getType();
    }

    @Override
    public String value17() {
        return getChannel();
    }

    @Override
    public Long value18() {
        return getCreatedAt();
    }

    @Override
    public Long value19() {
        return getUpdatedAt();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setClientUserId(value);
        return this;
    }

    @Override
    public UserRecord value4(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setIp(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserRecord value11(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserRecord value12(String value) {
        setLanguageCode(value);
        return this;
    }

    @Override
    public UserRecord value13(String value) {
        setLatitude(value);
        return this;
    }

    @Override
    public UserRecord value14(String value) {
        setLongitude(value);
        return this;
    }

    @Override
    public UserRecord value15(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public UserRecord value16(String value) {
        setType(value);
        return this;
    }

    @Override
    public UserRecord value17(String value) {
        setChannel(value);
        return this;
    }

    @Override
    public UserRecord value18(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserRecord value19(Long value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, Integer value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Integer value15, String value16, String value17, Long value18, Long value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, Integer version, String clientUserId, Integer level, String userName, String ip, String country, String city, String region, String firstName, String lastName, String languageCode, String latitude, String longitude, Integer status, String type, String channel, Long createdAt, Long updatedAt) {
        super(User.USER);

        setId(id);
        setVersion(version);
        setClientUserId(clientUserId);
        setLevel(level);
        setUserName(userName);
        setIp(ip);
        setCountry(country);
        setCity(city);
        setRegion(region);
        setFirstName(firstName);
        setLastName(lastName);
        setLanguageCode(languageCode);
        setLatitude(latitude);
        setLongitude(longitude);
        setStatus(status);
        setType(type);
        setChannel(channel);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(UserPo value) {
        super(User.USER);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setClientUserId(value.getClientUserId());
            setLevel(value.getLevel());
            setUserName(value.getUserName());
            setIp(value.getIp());
            setCountry(value.getCountry());
            setCity(value.getCity());
            setRegion(value.getRegion());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setLanguageCode(value.getLanguageCode());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setStatus(value.getStatus());
            setType(value.getType());
            setChannel(value.getChannel());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
