/*
 * This file is generated by jOOQ.
 */
package io.javalin.sample.db.write.tables.pojos;


import java.io.Serializable;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Integer version;
    private String  clientUserId;
    private Integer level;
    private String  userName;
    private String  ip;
    private String  country;
    private String  city;
    private String  region;
    private String  firstName;
    private String  lastName;
    private String  languageCode;
    private String  latitude;
    private String  longitude;
    private Integer status;
    private String  type;
    private String  channel;
    private Long    createdAt;
    private Long    updatedAt;

    public UserPo() {}

    public UserPo(UserPo value) {
        this.id = value.id;
        this.version = value.version;
        this.clientUserId = value.clientUserId;
        this.level = value.level;
        this.userName = value.userName;
        this.ip = value.ip;
        this.country = value.country;
        this.city = value.city;
        this.region = value.region;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.languageCode = value.languageCode;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.status = value.status;
        this.type = value.type;
        this.channel = value.channel;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public UserPo(
        Long    id,
        Integer version,
        String  clientUserId,
        Integer level,
        String  userName,
        String  ip,
        String  country,
        String  city,
        String  region,
        String  firstName,
        String  lastName,
        String  languageCode,
        String  latitude,
        String  longitude,
        Integer status,
        String  type,
        String  channel,
        Long    createdAt,
        Long    updatedAt
    ) {
        this.id = id;
        this.version = version;
        this.clientUserId = clientUserId;
        this.level = level;
        this.userName = userName;
        this.ip = ip;
        this.country = country;
        this.city = city;
        this.region = region;
        this.firstName = firstName;
        this.lastName = lastName;
        this.languageCode = languageCode;
        this.latitude = latitude;
        this.longitude = longitude;
        this.status = status;
        this.type = type;
        this.channel = channel;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>t_user.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>t_user.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>t_user.version</code>. 版本
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>t_user.version</code>. 版本
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for <code>t_user.client_user_id</code>. 小程序用户ID
     */
    public String getClientUserId() {
        return this.clientUserId;
    }

    /**
     * Setter for <code>t_user.client_user_id</code>. 小程序用户ID
     */
    public void setClientUserId(String clientUserId) {
        this.clientUserId = clientUserId;
    }

    /**
     * Getter for <code>t_user.level</code>. 等级
     */
    public Integer getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>t_user.level</code>. 等级
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * Getter for <code>t_user.user_name</code>. userName
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>t_user.user_name</code>. userName
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for <code>t_user.ip</code>. IP
     */
    public String getIp() {
        return this.ip;
    }

    /**
     * Setter for <code>t_user.ip</code>. IP
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * Getter for <code>t_user.country</code>. Country
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>t_user.country</code>. Country
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for <code>t_user.city</code>. city
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>t_user.city</code>. city
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>t_user.region</code>. region
     */
    public String getRegion() {
        return this.region;
    }

    /**
     * Setter for <code>t_user.region</code>. region
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * Getter for <code>t_user.first_name</code>. firstName
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>t_user.first_name</code>. firstName
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>t_user.last_name</code>. lastName
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>t_user.last_name</code>. lastName
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>t_user.language_code</code>. languageCode
     */
    public String getLanguageCode() {
        return this.languageCode;
    }

    /**
     * Setter for <code>t_user.language_code</code>. languageCode
     */
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    /**
     * Getter for <code>t_user.latitude</code>. latitude
     */
    public String getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>t_user.latitude</code>. latitude
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>t_user.longitude</code>. longitude
     */
    public String getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>t_user.longitude</code>. longitude
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for <code>t_user.status</code>.  状态
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>t_user.status</code>.  状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>t_user.type</code>. 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>t_user.type</code>. 类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>t_user.channel</code>. 渠道
     */
    public String getChannel() {
        return this.channel;
    }

    /**
     * Setter for <code>t_user.channel</code>. 渠道
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * Getter for <code>t_user.created_at</code>. 创建时间
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>t_user.created_at</code>. 创建时间
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>t_user.updated_at</code>. 更新时间
     */
    public Long getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>t_user.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPo (");

        sb.append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(clientUserId);
        sb.append(", ").append(level);
        sb.append(", ").append(userName);
        sb.append(", ").append(ip);
        sb.append(", ").append(country);
        sb.append(", ").append(city);
        sb.append(", ").append(region);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(languageCode);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(status);
        sb.append(", ").append(type);
        sb.append(", ").append(channel);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
