/*
 * This file is generated by jOOQ.
 */
package io.javalin.sample.db.write;


import io.javalin.sample.db.write.tables.OptionsFirmOrder;
import io.javalin.sample.db.write.tables.User;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户信息
     */
    public static final User USER = User.USER;

}
