<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-javalin-data-logs</artifactId>
    <description>
        ddd4j-javalin 数据层 - API 操作日志整合：
        Guice Module 注册 ApiOperationLogProvider，通过 Javalin Handler 拦截请求记录日志。
    </description>

    <dependencies>
        <!-- ddd4j 数据层日志纯 AspectJ 实现 -->
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-data-logs</artifactId>
            <version>${ddd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-runtime-guice</artifactId>
            <version>${ddd4j.version}</version>
        </dependency>
        <!-- Guice -->
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
        </dependency>
        <!-- Javalin -->
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
