<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.javalin</groupId>
        <artifactId>ddd4j-javalin-samples</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ddd4j-javalin-sample-auth-security</artifactId>
    <description>ddd4j-javalin-auth + Spring Security 风格集成示例（Javalin + Guice）</description>

    <dependencies>
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-guice</artifactId>
            <version>${ddd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.ddd4j.javalin</groupId>
            <artifactId>ddd4j-javalin-auth-security</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
        </dependency>
    </dependencies>

</project>
